// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: insights.sql

package ccdb

import (
	"context"
	"time"
)

const runInsights = `-- name: RunInsights :many
WITH days AS (
    SELECT generate_series($1::date, $2::date, interval '1 day')::date AS day
), matched AS (
    SELECT r.id, r.tokens_in, r.tokens_out, r.metrics_settled,
           (r.ended_at AT TIME ZONE $3::text)::date AS day
    FROM runs r
    JOIN tickets t ON t.url = r.ticket_id
    WHERE r.ended_at IS NOT NULL
      AND ($4::text = '' OR t.repo = $4)
      AND ($5::text = '' OR t.feature = $5)
)
SELECT d.day AS day,
       COALESCE(SUM(m.tokens_in), 0)::bigint AS tokens_in,
       COALESCE(SUM(m.tokens_out), 0)::bigint AS tokens_out,
       COUNT(m.id) AS runs,
       COUNT(*) FILTER (WHERE m.metrics_settled = false) AS unsettled
FROM days d
LEFT JOIN matched m ON m.day = d.day
GROUP BY d.day
ORDER BY d.day
`

type RunInsightsParams struct {
	Since    time.Time
	Until    time.Time
	Timezone string
	Repo     string
	Feature  string
}

type RunInsightsRow struct {
	Day       time.Time
	TokensIn  int64
	TokensOut int64
	Runs      int64
	Unsettled int64
}

// Every disposed run counts, tickets.withdrawn_at included (docs/adr/0015).
func (q *Queries) RunInsights(ctx context.Context, arg RunInsightsParams) ([]RunInsightsRow, error) {
	rows, err := q.db.QueryContext(ctx, runInsights,
		arg.Since,
		arg.Until,
		arg.Timezone,
		arg.Repo,
		arg.Feature,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunInsightsRow
	for rows.Next() {
		var i RunInsightsRow
		if err := rows.Scan(
			&i.Day,
			&i.TokensIn,
			&i.TokensOut,
			&i.Runs,
			&i.Unsettled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
