// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: launch.sql

package ccdb

import (
	"context"
	"database/sql"
)

const activeLaunchMemberCount = `-- name: ActiveLaunchMemberCount :one
SELECT COUNT(*) FROM launch_members WHERE launch_id IN (
    SELECT lm.launch_id FROM launch_members lm
    JOIN launches l ON l.id = lm.launch_id
    WHERE l.state = 'active' AND lm.ticket_id = $1
)
`

func (q *Queries) ActiveLaunchMemberCount(ctx context.Context, ticketID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, activeLaunchMemberCount, ticketID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const cancelActiveLaunches = `-- name: CancelActiveLaunches :exec
UPDATE launches SET state = 'cancelled' WHERE id IN (
    SELECT lm.launch_id FROM launch_members lm
    JOIN launches l ON l.id = lm.launch_id
    WHERE l.state = 'active' AND lm.ticket_id = $1
)
`

func (q *Queries) CancelActiveLaunches(ctx context.Context, ticketID string) error {
	_, err := q.db.ExecContext(ctx, cancelActiveLaunches, ticketID)
	return err
}

const consumeLaunchIntent = `-- name: ConsumeLaunchIntent :exec
UPDATE intents SET consumed_at = $1 WHERE id = $2
`

type ConsumeLaunchIntentParams struct {
	ConsumedAt sql.NullString
	ID         int64
}

func (q *Queries) ConsumeLaunchIntent(ctx context.Context, arg ConsumeLaunchIntentParams) error {
	_, err := q.db.ExecContext(ctx, consumeLaunchIntent, arg.ConsumedAt, arg.ID)
	return err
}

const insertLaunch = `-- name: InsertLaunch :one
INSERT INTO launches (created_at, state) VALUES ($1, 'active') RETURNING id
`

func (q *Queries) InsertLaunch(ctx context.Context, createdAt string) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertLaunch, createdAt)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertLaunchEvent = `-- name: InsertLaunchEvent :exec
INSERT INTO events (at, ticket_id, kind, detail) VALUES ($1, NULL, 'launch', $2)
`

type InsertLaunchEventParams struct {
	At     string
	Detail sql.NullString
}

func (q *Queries) InsertLaunchEvent(ctx context.Context, arg InsertLaunchEventParams) error {
	_, err := q.db.ExecContext(ctx, insertLaunchEvent, arg.At, arg.Detail)
	return err
}

const insertLaunchMember = `-- name: InsertLaunchMember :exec
INSERT INTO launch_members (launch_id, ticket_id, prompt_hash) VALUES ($1, $2, $3)
`

type InsertLaunchMemberParams struct {
	LaunchID   int64
	TicketID   string
	PromptHash string
}

func (q *Queries) InsertLaunchMember(ctx context.Context, arg InsertLaunchMemberParams) error {
	_, err := q.db.ExecContext(ctx, insertLaunchMember, arg.LaunchID, arg.TicketID, arg.PromptHash)
	return err
}

const launchMemberships = `-- name: LaunchMemberships :many
SELECT lm.ticket_id, lm.launch_id, l.state, lm.prompt_hash,
       COUNT(*) OVER (PARTITION BY lm.launch_id) AS members
FROM launch_members lm
JOIN launches l ON l.id = lm.launch_id
WHERE l.state IN ('active', 'cancelled')
`

type LaunchMembershipsRow struct {
	TicketID   string
	LaunchID   int64
	State      string
	PromptHash string
	Members    int64
}

func (q *Queries) LaunchMemberships(ctx context.Context) ([]LaunchMembershipsRow, error) {
	rows, err := q.db.QueryContext(ctx, launchMemberships)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LaunchMembershipsRow
	for rows.Next() {
		var i LaunchMembershipsRow
		if err := rows.Scan(
			&i.TicketID,
			&i.LaunchID,
			&i.State,
			&i.PromptHash,
			&i.Members,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pendingLaunchIntents = `-- name: PendingLaunchIntents :many
SELECT id, ticket_id, payload FROM intents WHERE verb = 'launch' AND consumed_at IS NULL ORDER BY id
`

type PendingLaunchIntentsRow struct {
	ID       int64
	TicketID string
	Payload  sql.NullString
}

func (q *Queries) PendingLaunchIntents(ctx context.Context) ([]PendingLaunchIntentsRow, error) {
	rows, err := q.db.QueryContext(ctx, pendingLaunchIntents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PendingLaunchIntentsRow
	for rows.Next() {
		var i PendingLaunchIntentsRow
		if err := rows.Scan(&i.ID, &i.TicketID, &i.Payload); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queueLaunchIntent = `-- name: QueueLaunchIntent :exec
INSERT INTO intents (at, ticket_id, verb, payload) VALUES ($1, $2, 'launch', $3)
`

type QueueLaunchIntentParams struct {
	At       string
	TicketID string
	Payload  sql.NullString
}

func (q *Queries) QueueLaunchIntent(ctx context.Context, arg QueueLaunchIntentParams) error {
	_, err := q.db.ExecContext(ctx, queueLaunchIntent, arg.At, arg.TicketID, arg.Payload)
	return err
}
