// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package ccdb

import (
	"database/sql"
	"time"
)

type Event struct {
	ID       int64
	At       time.Time
	TicketID sql.NullString
	Kind     string
	Detail   sql.NullString
}

type Intent struct {
	ID         int64
	At         time.Time
	TicketID   string
	Verb       string
	Payload    sql.NullString
	ConsumedAt sql.NullTime
}

type Launch struct {
	ID        int64
	CreatedAt time.Time
	State     string
}

type LaunchMember struct {
	LaunchID   int64
	TicketID   string
	PromptHash string
}

type Meta struct {
	Key   string
	Value string
}

type Push struct {
	ID            int64
	TicketID      string
	PushedTip     string
	BaseBranch    string
	BaseSHAAtPush string
	PushedAt      time.Time
}

type Run struct {
	ID            int64
	TicketID      string
	Kind          string
	Pgid          sql.NullInt64
	ProcStartedAt sql.NullTime
	BaselineSHA   sql.NullString
	PromptHash    sql.NullString
	LogPath       sql.NullString
	Outcome       sql.NullString
	ExitCode      sql.NullInt64
	EndedAt       sql.NullTime
}

type Ticket struct {
	URL       string
	Repo      string
	Branch    string
	BlockedBy string
	Source    string
	Title     string
	Body      string
	Status    string
	GroupKey  string
	SyncedAt  string
}
