// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pushes.sql

package ccdb

import (
	"context"
	"database/sql"
)

const lastPushedTips = `-- name: LastPushedTips :many
SELECT p.ticket_id, p.pushed_tip FROM pushes p
JOIN (SELECT ticket_id, MAX(id) AS id FROM pushes GROUP BY ticket_id) latest
  ON latest.ticket_id = p.ticket_id AND latest.id = p.id
`

type LastPushedTipsRow struct {
	TicketID  string
	PushedTip string
}

func (q *Queries) LastPushedTips(ctx context.Context) ([]LastPushedTipsRow, error) {
	rows, err := q.db.QueryContext(ctx, lastPushedTips)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LastPushedTipsRow
	for rows.Next() {
		var i LastPushedTipsRow
		if err := rows.Scan(&i.TicketID, &i.PushedTip); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const latestPushes = `-- name: LatestPushes :many
SELECT p.ticket_id, p.pushed_tip, p.base_branch, p.base_sha_at_push, p.pushed_at FROM pushes p
JOIN (SELECT ticket_id, MAX(id) AS id FROM pushes GROUP BY ticket_id) latest
  ON latest.ticket_id = p.ticket_id AND latest.id = p.id
`

type LatestPushesRow struct {
	TicketID      string
	PushedTip     string
	BaseBranch    string
	BaseSHAAtPush string
	PushedAt      string
}

func (q *Queries) LatestPushes(ctx context.Context) ([]LatestPushesRow, error) {
	rows, err := q.db.QueryContext(ctx, latestPushes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LatestPushesRow
	for rows.Next() {
		var i LatestPushesRow
		if err := rows.Scan(
			&i.TicketID,
			&i.PushedTip,
			&i.BaseBranch,
			&i.BaseSHAAtPush,
			&i.PushedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pushFacts = `-- name: PushFacts :many
SELECT e.ticket_id, e.kind, e.detail
FROM events e
JOIN (
    SELECT e2.ticket_id, MAX(e2.id) AS id
    FROM events e2
    LEFT JOIN (
        SELECT ticket_id, MAX(pushed_at) AS pushed_at FROM pushes GROUP BY ticket_id
    ) p ON p.ticket_id = e2.ticket_id
    WHERE e2.kind IN (?, ?) AND e2.at > COALESCE(p.pushed_at, '')
    GROUP BY e2.ticket_id
) latest ON latest.ticket_id = e.ticket_id AND latest.id = e.id
`

type PushFactsParams struct {
	Kind   string
	Kind_2 string
}

type PushFactsRow struct {
	TicketID sql.NullString
	Kind     string
	Detail   sql.NullString
}

func (q *Queries) PushFacts(ctx context.Context, arg PushFactsParams) ([]PushFactsRow, error) {
	rows, err := q.db.QueryContext(ctx, pushFacts, arg.Kind, arg.Kind_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PushFactsRow
	for rows.Next() {
		var i PushFactsRow
		if err := rows.Scan(&i.TicketID, &i.Kind, &i.Detail); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordPush = `-- name: RecordPush :exec
INSERT INTO pushes (ticket_id, pushed_tip, base_branch, base_sha_at_push, pushed_at)
VALUES (?, ?, ?, ?, ?)
`

type RecordPushParams struct {
	TicketID      string
	PushedTip     string
	BaseBranch    string
	BaseSHAAtPush string
	PushedAt      string
}

func (q *Queries) RecordPush(ctx context.Context, arg RecordPushParams) error {
	_, err := q.db.ExecContext(ctx, recordPush,
		arg.TicketID,
		arg.PushedTip,
		arg.BaseBranch,
		arg.BaseSHAAtPush,
		arg.PushedAt,
	)
	return err
}

const restackedSinceLastPush = `-- name: RestackedSinceLastPush :many
SELECT DISTINCT e.ticket_id
FROM events e
LEFT JOIN (
    SELECT ticket_id, MAX(pushed_at) AS pushed_at FROM pushes GROUP BY ticket_id
) p ON p.ticket_id = e.ticket_id
WHERE e.kind = ? AND e.at >= COALESCE(p.pushed_at, '')
`

func (q *Queries) RestackedSinceLastPush(ctx context.Context, kind string) ([]sql.NullString, error) {
	rows, err := q.db.QueryContext(ctx, restackedSinceLastPush, kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []sql.NullString
	for rows.Next() {
		var ticket_id sql.NullString
		if err := rows.Scan(&ticket_id); err != nil {
			return nil, err
		}
		items = append(items, ticket_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
