// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh.sql

package ccdb

import (
	"context"
	"database/sql"
	"strings"
)

const latestRefreshOutcomes = `-- name: LatestRefreshOutcomes :many
SELECT e.ticket_id, e.kind, e.detail
FROM events e
JOIN (
    SELECT e2.ticket_id, MAX(e2.id) AS id
    FROM events e2
    LEFT JOIN (
        SELECT ticket_id, MAX(pushed_at) AS pushed_at FROM pushes GROUP BY ticket_id
    ) p ON p.ticket_id = e2.ticket_id
    WHERE e2.kind IN (/*SLICE:kinds*/?) AND e2.at > COALESCE(p.pushed_at, '')
    GROUP BY e2.ticket_id
) latest ON latest.ticket_id = e.ticket_id AND latest.id = e.id
`

type LatestRefreshOutcomesRow struct {
	TicketID sql.NullString
	Kind     string
	Detail   sql.NullString
}

func (q *Queries) LatestRefreshOutcomes(ctx context.Context, kinds []string) ([]LatestRefreshOutcomesRow, error) {
	query := latestRefreshOutcomes
	var queryParams []interface{}
	if len(kinds) > 0 {
		for _, v := range kinds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:kinds*/?", strings.Repeat(",?", len(kinds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:kinds*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LatestRefreshOutcomesRow
	for rows.Next() {
		var i LatestRefreshOutcomesRow
		if err := rows.Scan(&i.TicketID, &i.Kind, &i.Detail); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
