// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: removal.sql

package ccdb

import (
	"context"
	"database/sql"
)

const latestRemovalRefusals = `-- name: LatestRemovalRefusals :many
SELECT e.ticket_id, e.detail
FROM events e
JOIN (
    SELECT e2.ticket_id, MAX(e2.id) AS id FROM events e2 WHERE e2.kind = $1 GROUP BY e2.ticket_id
) latest ON latest.ticket_id = e.ticket_id AND latest.id = e.id
`

type LatestRemovalRefusalsRow struct {
	TicketID sql.NullString
	Detail   sql.NullString
}

func (q *Queries) LatestRemovalRefusals(ctx context.Context, kind string) ([]LatestRemovalRefusalsRow, error) {
	rows, err := q.db.QueryContext(ctx, latestRemovalRefusals, kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LatestRemovalRefusalsRow
	for rows.Next() {
		var i LatestRemovalRefusalsRow
		if err := rows.Scan(&i.TicketID, &i.Detail); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
