// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runs.sql

package ccdb

import (
	"context"
	"database/sql"
)

const activeLaunchHashes = `-- name: ActiveLaunchHashes :many
SELECT lm.ticket_id, lm.prompt_hash FROM launch_members lm
JOIN launches l ON l.id = lm.launch_id
WHERE l.state = 'active'
`

type ActiveLaunchHashesRow struct {
	TicketID   string
	PromptHash string
}

func (q *Queries) ActiveLaunchHashes(ctx context.Context) ([]ActiveLaunchHashesRow, error) {
	rows, err := q.db.QueryContext(ctx, activeLaunchHashes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActiveLaunchHashesRow
	for rows.Next() {
		var i ActiveLaunchHashesRow
		if err := rows.Scan(&i.TicketID, &i.PromptHash); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const consumeVerbIntent = `-- name: ConsumeVerbIntent :exec
UPDATE intents SET consumed_at = $1 WHERE id = $2
`

type ConsumeVerbIntentParams struct {
	ConsumedAt sql.NullString
	ID         int64
}

func (q *Queries) ConsumeVerbIntent(ctx context.Context, arg ConsumeVerbIntentParams) error {
	_, err := q.db.ExecContext(ctx, consumeVerbIntent, arg.ConsumedAt, arg.ID)
	return err
}

const insertCutFailedRun = `-- name: InsertCutFailedRun :one
INSERT INTO runs (ticket_id, kind, prompt_hash, outcome, ended_at)
VALUES ($1, 'agent', $2, $3, $4) RETURNING id
`

type InsertCutFailedRunParams struct {
	TicketID   string
	PromptHash sql.NullString
	Outcome    sql.NullString
	EndedAt    sql.NullString
}

func (q *Queries) InsertCutFailedRun(ctx context.Context, arg InsertCutFailedRunParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertCutFailedRun,
		arg.TicketID,
		arg.PromptHash,
		arg.Outcome,
		arg.EndedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertRunSkeleton = `-- name: InsertRunSkeleton :one
INSERT INTO runs (ticket_id, kind, baseline_sha, prompt_hash) VALUES ($1, $2, $3, $4) RETURNING id
`

type InsertRunSkeletonParams struct {
	TicketID    string
	Kind        string
	BaselineSHA sql.NullString
	PromptHash  sql.NullString
}

func (q *Queries) InsertRunSkeleton(ctx context.Context, arg InsertRunSkeletonParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertRunSkeleton,
		arg.TicketID,
		arg.Kind,
		arg.BaselineSHA,
		arg.PromptHash,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const latestRunLog = `-- name: LatestRunLog :one
SELECT log_path, ended_at FROM runs WHERE ticket_id = $1 ORDER BY id DESC LIMIT 1
`

type LatestRunLogRow struct {
	LogPath sql.NullString
	EndedAt sql.NullString
}

func (q *Queries) LatestRunLog(ctx context.Context, ticketID string) (LatestRunLogRow, error) {
	row := q.db.QueryRowContext(ctx, latestRunLog, ticketID)
	var i LatestRunLogRow
	err := row.Scan(&i.LogPath, &i.EndedAt)
	return i, err
}

const latestRunsByTicket = `-- name: LatestRunsByTicket :many
SELECT r.id, r.ticket_id, r.pgid, r.proc_started_at, r.baseline_sha, r.log_path,
       r.outcome, r.exit_code, r.ended_at, r.prompt_hash, r.kind
FROM runs r
JOIN (SELECT ticket_id, MAX(id) AS id FROM runs GROUP BY ticket_id) latest
  ON latest.ticket_id = r.ticket_id AND latest.id = r.id
`

type LatestRunsByTicketRow struct {
	ID            int64
	TicketID      string
	Pgid          sql.NullInt64
	ProcStartedAt sql.NullString
	BaselineSHA   sql.NullString
	LogPath       sql.NullString
	Outcome       sql.NullString
	ExitCode      sql.NullInt64
	EndedAt       sql.NullString
	PromptHash    sql.NullString
	Kind          string
}

func (q *Queries) LatestRunsByTicket(ctx context.Context) ([]LatestRunsByTicketRow, error) {
	rows, err := q.db.QueryContext(ctx, latestRunsByTicket)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LatestRunsByTicketRow
	for rows.Next() {
		var i LatestRunsByTicketRow
		if err := rows.Scan(
			&i.ID,
			&i.TicketID,
			&i.Pgid,
			&i.ProcStartedAt,
			&i.BaselineSHA,
			&i.LogPath,
			&i.Outcome,
			&i.ExitCode,
			&i.EndedAt,
			&i.PromptHash,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pendingIntentsByTicket = `-- name: PendingIntentsByTicket :many
SELECT ticket_id, verb FROM intents WHERE consumed_at IS NULL ORDER BY id
`

type PendingIntentsByTicketRow struct {
	TicketID string
	Verb     string
}

func (q *Queries) PendingIntentsByTicket(ctx context.Context) ([]PendingIntentsByTicketRow, error) {
	rows, err := q.db.QueryContext(ctx, pendingIntentsByTicket)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PendingIntentsByTicketRow
	for rows.Next() {
		var i PendingIntentsByTicketRow
		if err := rows.Scan(&i.TicketID, &i.Verb); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pendingRunsAwaitingDisposition = `-- name: PendingRunsAwaitingDisposition :many
SELECT id, ticket_id, pgid, proc_started_at, baseline_sha, log_path FROM runs
WHERE pgid IS NOT NULL AND outcome IS NULL
`

type PendingRunsAwaitingDispositionRow struct {
	ID            int64
	TicketID      string
	Pgid          sql.NullInt64
	ProcStartedAt sql.NullString
	BaselineSHA   sql.NullString
	LogPath       sql.NullString
}

func (q *Queries) PendingRunsAwaitingDisposition(ctx context.Context) ([]PendingRunsAwaitingDispositionRow, error) {
	rows, err := q.db.QueryContext(ctx, pendingRunsAwaitingDisposition)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PendingRunsAwaitingDispositionRow
	for rows.Next() {
		var i PendingRunsAwaitingDispositionRow
		if err := rows.Scan(
			&i.ID,
			&i.TicketID,
			&i.Pgid,
			&i.ProcStartedAt,
			&i.BaselineSHA,
			&i.LogPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pendingVerbIntents = `-- name: PendingVerbIntents :many
SELECT id, ticket_id FROM intents WHERE verb = $1 AND consumed_at IS NULL ORDER BY id
`

type PendingVerbIntentsRow struct {
	ID       int64
	TicketID string
}

func (q *Queries) PendingVerbIntents(ctx context.Context, verb string) ([]PendingVerbIntentsRow, error) {
	rows, err := q.db.QueryContext(ctx, pendingVerbIntents, verb)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PendingVerbIntentsRow
	for rows.Next() {
		var i PendingVerbIntentsRow
		if err := rows.Scan(&i.ID, &i.TicketID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queueVerbIntent = `-- name: QueueVerbIntent :exec
INSERT INTO intents (at, ticket_id, verb) VALUES ($1, $2, $3)
`

type QueueVerbIntentParams struct {
	At       string
	TicketID string
	Verb     string
}

func (q *Queries) QueueVerbIntent(ctx context.Context, arg QueueVerbIntentParams) error {
	_, err := q.db.ExecContext(ctx, queueVerbIntent, arg.At, arg.TicketID, arg.Verb)
	return err
}

const recordDisposition = `-- name: RecordDisposition :exec
UPDATE runs SET outcome = $1, exit_code = $2, ended_at = $3 WHERE id = $4
`

type RecordDispositionParams struct {
	Outcome  sql.NullString
	ExitCode sql.NullInt64
	EndedAt  sql.NullString
	ID       int64
}

func (q *Queries) RecordDisposition(ctx context.Context, arg RecordDispositionParams) error {
	_, err := q.db.ExecContext(ctx, recordDisposition,
		arg.Outcome,
		arg.ExitCode,
		arg.EndedAt,
		arg.ID,
	)
	return err
}

const recordSpawn = `-- name: RecordSpawn :exec
UPDATE runs SET pgid = $1, proc_started_at = $2, log_path = $3 WHERE id = $4
`

type RecordSpawnParams struct {
	Pgid          sql.NullInt64
	ProcStartedAt sql.NullString
	LogPath       sql.NullString
	ID            int64
}

func (q *Queries) RecordSpawn(ctx context.Context, arg RecordSpawnParams) error {
	_, err := q.db.ExecContext(ctx, recordSpawn,
		arg.Pgid,
		arg.ProcStartedAt,
		arg.LogPath,
		arg.ID,
	)
	return err
}

const runIDsForTicket = `-- name: RunIDsForTicket :many
SELECT id FROM runs WHERE ticket_id = $1 ORDER BY id
`

func (q *Queries) RunIDsForTicket(ctx context.Context, ticketID string) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, runIDsForTicket, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
