// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: store.sql

package ccdb

import (
	"context"
	"database/sql"
	"encoding/json"
)

const appendEvent = `-- name: AppendEvent :exec
INSERT INTO events (at, ticket_id, kind, detail) VALUES ($1, $2, $3, $4)
`

type AppendEventParams struct {
	At       string
	TicketID sql.NullString
	Kind     string
	Detail   sql.NullString
}

func (q *Queries) AppendEvent(ctx context.Context, arg AppendEventParams) error {
	_, err := q.db.ExecContext(ctx, appendEvent,
		arg.At,
		arg.TicketID,
		arg.Kind,
		arg.Detail,
	)
	return err
}

const deleteLaunchMembersForTicket = `-- name: DeleteLaunchMembersForTicket :exec
DELETE FROM launch_members WHERE ticket_id = $1
`

func (q *Queries) DeleteLaunchMembersForTicket(ctx context.Context, ticketID string) error {
	_, err := q.db.ExecContext(ctx, deleteLaunchMembersForTicket, ticketID)
	return err
}

const deletePushesForTicket = `-- name: DeletePushesForTicket :exec
DELETE FROM pushes WHERE ticket_id = $1
`

func (q *Queries) DeletePushesForTicket(ctx context.Context, ticketID string) error {
	_, err := q.db.ExecContext(ctx, deletePushesForTicket, ticketID)
	return err
}

const deleteRunsForTicket = `-- name: DeleteRunsForTicket :exec
DELETE FROM runs WHERE ticket_id = $1
`

func (q *Queries) DeleteRunsForTicket(ctx context.Context, ticketID string) error {
	_, err := q.db.ExecContext(ctx, deleteRunsForTicket, ticketID)
	return err
}

const deleteTicket = `-- name: DeleteTicket :exec
DELETE FROM tickets WHERE url = $1
`

func (q *Queries) DeleteTicket(ctx context.Context, url string) error {
	_, err := q.db.ExecContext(ctx, deleteTicket, url)
	return err
}

const events = `-- name: Events :many
SELECT at, ticket_id, kind, detail FROM events ORDER BY id
`

type EventsRow struct {
	At       string
	TicketID sql.NullString
	Kind     string
	Detail   sql.NullString
}

func (q *Queries) Events(ctx context.Context) ([]EventsRow, error) {
	rows, err := q.db.QueryContext(ctx, events)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventsRow
	for rows.Next() {
		var i EventsRow
		if err := rows.Scan(
			&i.At,
			&i.TicketID,
			&i.Kind,
			&i.Detail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMeta = `-- name: GetMeta :one
SELECT value FROM meta WHERE key = $1
`

func (q *Queries) GetMeta(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getMeta, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const importTicket = `-- name: ImportTicket :exec
INSERT INTO tickets (url, repo, source, group_key, title, body, status, synced_at, branch, blocked_by)
VALUES ($1, $2, 'github', $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (url) DO UPDATE SET
    repo = excluded.repo, source = excluded.source, group_key = excluded.group_key,
    title = excluded.title, body = excluded.body, status = excluded.status,
    synced_at = excluded.synced_at
`

type ImportTicketParams struct {
	URL       string
	Repo      string
	GroupKey  string
	Title     string
	Body      string
	Status    string
	SyncedAt  string
	Branch    string
	BlockedBy json.RawMessage
}

func (q *Queries) ImportTicket(ctx context.Context, arg ImportTicketParams) error {
	_, err := q.db.ExecContext(ctx, importTicket,
		arg.URL,
		arg.Repo,
		arg.GroupKey,
		arg.Title,
		arg.Body,
		arg.Status,
		arg.SyncedAt,
		arg.Branch,
		arg.BlockedBy,
	)
	return err
}

const putMeta = `-- name: PutMeta :exec
INSERT INTO meta (key, value) VALUES ($1, $2)
ON CONFLICT (key) DO UPDATE SET value = excluded.value
`

type PutMetaParams struct {
	Key   string
	Value string
}

func (q *Queries) PutMeta(ctx context.Context, arg PutMetaParams) error {
	_, err := q.db.ExecContext(ctx, putMeta, arg.Key, arg.Value)
	return err
}

const tickets = `-- name: Tickets :many
SELECT url, repo, branch, blocked_by, source, title, body, status, group_key, synced_at
FROM tickets ORDER BY url
`

func (q *Queries) Tickets(ctx context.Context) ([]Ticket, error) {
	rows, err := q.db.QueryContext(ctx, tickets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.URL,
			&i.Repo,
			&i.Branch,
			&i.BlockedBy,
			&i.Source,
			&i.Title,
			&i.Body,
			&i.Status,
			&i.GroupKey,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTicket = `-- name: UpsertTicket :exec
INSERT INTO tickets (url, repo, branch, blocked_by, source, title, body, status, group_key, synced_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (url) DO UPDATE SET
    repo = excluded.repo, branch = excluded.branch, blocked_by = excluded.blocked_by,
    source = excluded.source, title = excluded.title, body = excluded.body,
    status = excluded.status, group_key = excluded.group_key, synced_at = excluded.synced_at
`

type UpsertTicketParams struct {
	URL       string
	Repo      string
	Branch    string
	BlockedBy json.RawMessage
	Source    string
	Title     string
	Body      string
	Status    string
	GroupKey  string
	SyncedAt  string
}

func (q *Queries) UpsertTicket(ctx context.Context, arg UpsertTicketParams) error {
	_, err := q.db.ExecContext(ctx, upsertTicket,
		arg.URL,
		arg.Repo,
		arg.Branch,
		arg.BlockedBy,
		arg.Source,
		arg.Title,
		arg.Body,
		arg.Status,
		arg.GroupKey,
		arg.SyncedAt,
	)
	return err
}
