// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: store.sql

package ccdb

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const appendEvent = `-- name: AppendEvent :exec
INSERT INTO events (at, ticket_id, kind, detail) VALUES ($1, $2, $3, $4)
`

type AppendEventParams struct {
	At       time.Time
	TicketID sql.NullString
	Kind     string
	Detail   sql.NullString
}

func (q *Queries) AppendEvent(ctx context.Context, arg AppendEventParams) error {
	_, err := q.db.ExecContext(ctx, appendEvent,
		arg.At,
		arg.TicketID,
		arg.Kind,
		arg.Detail,
	)
	return err
}

const events = `-- name: Events :many
SELECT at, ticket_id, kind, detail FROM events ORDER BY id
`

type EventsRow struct {
	At       time.Time
	TicketID sql.NullString
	Kind     string
	Detail   sql.NullString
}

func (q *Queries) Events(ctx context.Context) ([]EventsRow, error) {
	rows, err := q.db.QueryContext(ctx, events)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventsRow
	for rows.Next() {
		var i EventsRow
		if err := rows.Scan(
			&i.At,
			&i.TicketID,
			&i.Kind,
			&i.Detail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMeta = `-- name: GetMeta :one
SELECT value FROM meta WHERE key = $1
`

func (q *Queries) GetMeta(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getMeta, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const importTicket = `-- name: ImportTicket :exec
INSERT INTO tickets (url, repo, source, feature, title, body, status, synced_at, branch, blocked_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (url) DO UPDATE SET
    repo = excluded.repo, source = excluded.source, feature = excluded.feature,
    title = excluded.title, body = excluded.body, status = excluded.status,
    synced_at = excluded.synced_at, withdrawn_at = NULL
`

type ImportTicketParams struct {
	URL       string
	Repo      string
	Source    string
	Feature   string
	Title     string
	Body      string
	Status    string
	SyncedAt  string
	Branch    string
	BlockedBy json.RawMessage
}

func (q *Queries) ImportTicket(ctx context.Context, arg ImportTicketParams) error {
	_, err := q.db.ExecContext(ctx, importTicket,
		arg.URL,
		arg.Repo,
		arg.Source,
		arg.Feature,
		arg.Title,
		arg.Body,
		arg.Status,
		arg.SyncedAt,
		arg.Branch,
		arg.BlockedBy,
	)
	return err
}

const putMeta = `-- name: PutMeta :exec
INSERT INTO meta (key, value) VALUES ($1, $2)
ON CONFLICT (key) DO UPDATE SET value = excluded.value
`

type PutMetaParams struct {
	Key   string
	Value string
}

func (q *Queries) PutMeta(ctx context.Context, arg PutMetaParams) error {
	_, err := q.db.ExecContext(ctx, putMeta, arg.Key, arg.Value)
	return err
}

const setBlockedBy = `-- name: SetBlockedBy :exec
UPDATE tickets SET blocked_by = $1 WHERE url = $2
`

type SetBlockedByParams struct {
	BlockedBy json.RawMessage
	URL       string
}

func (q *Queries) SetBlockedBy(ctx context.Context, arg SetBlockedByParams) error {
	_, err := q.db.ExecContext(ctx, setBlockedBy, arg.BlockedBy, arg.URL)
	return err
}

const ticketFeature = `-- name: TicketFeature :one
SELECT feature FROM tickets WHERE url = $1 AND withdrawn_at IS NULL
`

func (q *Queries) TicketFeature(ctx context.Context, url string) (string, error) {
	row := q.db.QueryRowContext(ctx, ticketFeature, url)
	var feature string
	err := row.Scan(&feature)
	return feature, err
}

const tickets = `-- name: Tickets :many
SELECT url, repo, branch, blocked_by, source, title, body, status, feature, synced_at
FROM tickets WHERE withdrawn_at IS NULL ORDER BY url
`

type TicketsRow struct {
	URL       string
	Repo      string
	Branch    string
	BlockedBy json.RawMessage
	Source    string
	Title     string
	Body      string
	Status    string
	Feature   string
	SyncedAt  string
}

func (q *Queries) Tickets(ctx context.Context) ([]TicketsRow, error) {
	rows, err := q.db.QueryContext(ctx, tickets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TicketsRow
	for rows.Next() {
		var i TicketsRow
		if err := rows.Scan(
			&i.URL,
			&i.Repo,
			&i.Branch,
			&i.BlockedBy,
			&i.Source,
			&i.Title,
			&i.Body,
			&i.Status,
			&i.Feature,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ticketsInFeature = `-- name: TicketsInFeature :many
SELECT url, repo, branch FROM tickets WHERE feature = $1
`

type TicketsInFeatureRow struct {
	URL    string
	Repo   string
	Branch string
}

func (q *Queries) TicketsInFeature(ctx context.Context, feature string) ([]TicketsInFeatureRow, error) {
	rows, err := q.db.QueryContext(ctx, ticketsInFeature, feature)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TicketsInFeatureRow
	for rows.Next() {
		var i TicketsInFeatureRow
		if err := rows.Scan(&i.URL, &i.Repo, &i.Branch); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ticketsWithBlockers = `-- name: TicketsWithBlockers :many
SELECT url, blocked_by FROM tickets WHERE withdrawn_at IS NULL
`

type TicketsWithBlockersRow struct {
	URL       string
	BlockedBy json.RawMessage
}

func (q *Queries) TicketsWithBlockers(ctx context.Context) ([]TicketsWithBlockersRow, error) {
	rows, err := q.db.QueryContext(ctx, ticketsWithBlockers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TicketsWithBlockersRow
	for rows.Next() {
		var i TicketsWithBlockersRow
		if err := rows.Scan(&i.URL, &i.BlockedBy); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTicket = `-- name: UpsertTicket :exec
INSERT INTO tickets (url, repo, branch, blocked_by, source, title, body, status, feature, synced_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (url) DO UPDATE SET
    repo = excluded.repo, branch = excluded.branch, blocked_by = excluded.blocked_by,
    source = excluded.source, title = excluded.title, body = excluded.body,
    status = excluded.status, feature = excluded.feature, synced_at = excluded.synced_at
`

type UpsertTicketParams struct {
	URL       string
	Repo      string
	Branch    string
	BlockedBy json.RawMessage
	Source    string
	Title     string
	Body      string
	Status    string
	Feature   string
	SyncedAt  string
}

func (q *Queries) UpsertTicket(ctx context.Context, arg UpsertTicketParams) error {
	_, err := q.db.ExecContext(ctx, upsertTicket,
		arg.URL,
		arg.Repo,
		arg.Branch,
		arg.BlockedBy,
		arg.Source,
		arg.Title,
		arg.Body,
		arg.Status,
		arg.Feature,
		arg.SyncedAt,
	)
	return err
}

const withdrawTicket = `-- name: WithdrawTicket :exec
UPDATE tickets SET withdrawn_at = $1 WHERE url = $2 AND withdrawn_at IS NULL
`

type WithdrawTicketParams struct {
	WithdrawnAt sql.NullTime
	URL         string
}

func (q *Queries) WithdrawTicket(ctx context.Context, arg WithdrawTicketParams) error {
	_, err := q.db.ExecContext(ctx, withdrawTicket, arg.WithdrawnAt, arg.URL)
	return err
}
