// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ticket_edit.sql

package ccdb

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const editTicket = `-- name: EditTicket :exec
UPDATE tickets SET branch = $1, blocked_by = $2 WHERE url = $3
`

type EditTicketParams struct {
	Branch    string
	BlockedBy json.RawMessage
	URL       string
}

func (q *Queries) EditTicket(ctx context.Context, arg EditTicketParams) error {
	_, err := q.db.ExecContext(ctx, editTicket, arg.Branch, arg.BlockedBy, arg.URL)
	return err
}

const pendingEditTicketIntents = `-- name: PendingEditTicketIntents :many
SELECT id, ticket_id, payload FROM intents WHERE verb = 'edit_ticket' AND consumed_at IS NULL ORDER BY id
`

type PendingEditTicketIntentsRow struct {
	ID       int64
	TicketID string
	Payload  sql.NullString
}

func (q *Queries) PendingEditTicketIntents(ctx context.Context) ([]PendingEditTicketIntentsRow, error) {
	rows, err := q.db.QueryContext(ctx, pendingEditTicketIntents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PendingEditTicketIntentsRow
	for rows.Next() {
		var i PendingEditTicketIntentsRow
		if err := rows.Scan(&i.ID, &i.TicketID, &i.Payload); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queueEditTicketIntent = `-- name: QueueEditTicketIntent :exec
INSERT INTO intents (at, ticket_id, verb, payload) VALUES ($1, $2, 'edit_ticket', $3)
`

type QueueEditTicketIntentParams struct {
	At       time.Time
	TicketID string
	Payload  sql.NullString
}

func (q *Queries) QueueEditTicketIntent(ctx context.Context, arg QueueEditTicketIntentParams) error {
	_, err := q.db.ExecContext(ctx, queueEditTicketIntent, arg.At, arg.TicketID, arg.Payload)
	return err
}
