package tracker

import (
	"fmt"
	"strconv"
	"strings"
)

// BranchSlug is the branch name generated for a ticket: cc-<number>-<title, slugified>.
func BranchSlug(number int, title string) string {
	return fmt.Sprintf("cc-%d-%s", number, slugify(title))
}

// BranchNumber recovers the ticket number BranchSlug encoded, and false for a branch that was
// never generated by it -- never true for a hand-typed or third-party branch name.
func BranchNumber(branch string) (int, bool) {
	rest, ok := strings.CutPrefix(branch, "cc-")
	if !ok {
		return 0, false
	}
	numStr, _, _ := strings.Cut(rest, "-")
	n, err := strconv.Atoi(numStr)
	if err != nil {
		return 0, false
	}
	return n, true
}

func slugify(title string) string {
	var b strings.Builder
	atHyphen := true
	for _, r := range strings.ToLower(title) {
		switch {
		case r >= 'a' && r <= 'z' || r >= '0' && r <= '9':
			b.WriteRune(r)
			atHyphen = false
		case !atHyphen:
			b.WriteByte('-')
			atHyphen = true
		}
	}
	return strings.TrimSuffix(b.String(), "-")
}
