// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: repos.sql

package ccdb

import (
	"context"
	"database/sql"
	"time"
)

const renameTicketRepo = `-- name: RenameTicketRepo :exec
UPDATE tickets SET repo = $1 WHERE repo = $2
`

type RenameTicketRepoParams struct {
	NewName string
	OldName string
}

func (q *Queries) RenameTicketRepo(ctx context.Context, arg RenameTicketRepoParams) error {
	_, err := q.db.ExecContext(ctx, renameTicketRepo, arg.NewName, arg.OldName)
	return err
}

const repos = `-- name: Repos :many
SELECT name, remote, state, refusal_kind, refusal, settings_source, settings_read_at, tracked_at
FROM repos ORDER BY name
`

func (q *Queries) Repos(ctx context.Context) ([]Repo, error) {
	rows, err := q.db.QueryContext(ctx, repos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repo
	for rows.Next() {
		var i Repo
		if err := rows.Scan(
			&i.Name,
			&i.Remote,
			&i.State,
			&i.RefusalKind,
			&i.Refusal,
			&i.SettingsSource,
			&i.SettingsReadAt,
			&i.TrackedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRepoState = `-- name: SetRepoState :exec
UPDATE repos SET state = $2, refusal_kind = $3, refusal = $4, settings_source = $5, settings_read_at = $6
WHERE name = $1
`

type SetRepoStateParams struct {
	Name           string
	State          string
	RefusalKind    sql.NullString
	Refusal        sql.NullString
	SettingsSource sql.NullString
	SettingsReadAt sql.NullTime
}

func (q *Queries) SetRepoState(ctx context.Context, arg SetRepoStateParams) error {
	_, err := q.db.ExecContext(ctx, setRepoState,
		arg.Name,
		arg.State,
		arg.RefusalKind,
		arg.Refusal,
		arg.SettingsSource,
		arg.SettingsReadAt,
	)
	return err
}

const upsertRepo = `-- name: UpsertRepo :exec
INSERT INTO repos (name, remote, state, refusal_kind, refusal, tracked_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (name) DO UPDATE SET
    remote = EXCLUDED.remote, state = EXCLUDED.state,
    refusal_kind = EXCLUDED.refusal_kind, refusal = EXCLUDED.refusal
`

type UpsertRepoParams struct {
	Name        string
	Remote      string
	State       string
	RefusalKind sql.NullString
	Refusal     sql.NullString
	TrackedAt   time.Time
}

func (q *Queries) UpsertRepo(ctx context.Context, arg UpsertRepoParams) error {
	_, err := q.db.ExecContext(ctx, upsertRepo,
		arg.Name,
		arg.Remote,
		arg.State,
		arg.RefusalKind,
		arg.Refusal,
		arg.TrackedAt,
	)
	return err
}
