// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: utilization_intervals.sql

package ccdb

import (
	"context"
	"database/sql"
	"time"
)

const cCCostSince = `-- name: CCCostSince :one
SELECT
    COALESCE(SUM(cost_usd) FILTER (WHERE ended_at >= $1), 0)::double precision AS five_hour_usd,
    COALESCE(SUM(cost_usd) FILTER (WHERE ended_at >= $2), 0)::double precision AS seven_day_usd
FROM runs
WHERE cost_usd IS NOT NULL
`

type CCCostSinceParams struct {
	FiveHourSince sql.NullTime
	SevenDaySince sql.NullTime
}

type CCCostSinceRow struct {
	FiveHourUsd float64
	SevenDayUsd float64
}

func (q *Queries) CCCostSince(ctx context.Context, arg CCCostSinceParams) (CCCostSinceRow, error) {
	row := q.db.QueryRowContext(ctx, cCCostSince, arg.FiveHourSince, arg.SevenDaySince)
	var i CCCostSinceRow
	err := row.Scan(&i.FiveHourUsd, &i.SevenDayUsd)
	return i, err
}

const intervalsSince = `-- name: IntervalsSince :many
SELECT "window", start_at, end_at, utilization_start, utilization_end, weight_usd
FROM utilization_intervals
WHERE end_at >= $1
ORDER BY "window", start_at
`

type IntervalsSinceRow struct {
	Window           string
	StartAt          time.Time
	EndAt            time.Time
	UtilizationStart float64
	UtilizationEnd   float64
	WeightUsd        float64
}

func (q *Queries) IntervalsSince(ctx context.Context, endAt time.Time) ([]IntervalsSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, intervalsSince, endAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IntervalsSinceRow
	for rows.Next() {
		var i IntervalsSinceRow
		if err := rows.Scan(
			&i.Window,
			&i.StartAt,
			&i.EndAt,
			&i.UtilizationStart,
			&i.UtilizationEnd,
			&i.WeightUsd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordInterval = `-- name: RecordInterval :exec
INSERT INTO utilization_intervals (
    "window", start_at, end_at, utilization_start, utilization_end, weight_usd
) VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT ("window", start_at) DO NOTHING
`

type RecordIntervalParams struct {
	Window           string
	StartAt          time.Time
	EndAt            time.Time
	UtilizationStart float64
	UtilizationEnd   float64
	WeightUsd        float64
}

func (q *Queries) RecordInterval(ctx context.Context, arg RecordIntervalParams) error {
	_, err := q.db.ExecContext(ctx, recordInterval,
		arg.Window,
		arg.StartAt,
		arg.EndAt,
		arg.UtilizationStart,
		arg.UtilizationEnd,
		arg.WeightUsd,
	)
	return err
}
