// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: utilization_readings.sql

package ccdb

import (
	"context"
	"time"
)

const latestReadingsFull = `-- name: LatestReadingsFull :many
SELECT DISTINCT ON ("window") "window", at, utilization, resets_at
FROM utilization_readings
ORDER BY "window", at DESC
`

type LatestReadingsFullRow struct {
	Window      string
	At          time.Time
	Utilization float64
	ResetsAt    time.Time
}

func (q *Queries) LatestReadingsFull(ctx context.Context) ([]LatestReadingsFullRow, error) {
	rows, err := q.db.QueryContext(ctx, latestReadingsFull)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LatestReadingsFullRow
	for rows.Next() {
		var i LatestReadingsFullRow
		if err := rows.Scan(
			&i.Window,
			&i.At,
			&i.Utilization,
			&i.ResetsAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordReading = `-- name: RecordReading :exec
INSERT INTO utilization_readings (at, "window", utilization, resets_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (at, "window") DO NOTHING
`

type RecordReadingParams struct {
	At          time.Time
	Window      string
	Utilization float64
	ResetsAt    time.Time
}

func (q *Queries) RecordReading(ctx context.Context, arg RecordReadingParams) error {
	_, err := q.db.ExecContext(ctx, recordReading,
		arg.At,
		arg.Window,
		arg.Utilization,
		arg.ResetsAt,
	)
	return err
}
